// ---------------------------------------------------------------------
// CRM types — must match Supabase CRM tables schema
// ---------------------------------------------------------------------

// ============================================================
// Student
// ============================================================

export interface Student {
  id: string;
  first_name: string;
  last_name: string;
  photo_url: string | null;
  email: string | null;
  phone: string | null;
  facebook_url: string | null;
  instagram_url: string | null;
  notes_health: string | null;
  notes_family: string | null;
  notes_hobbies: string | null;
  notes_other: string | null;
  holiday_until: string | null; // ISO date string (YYYY-MM-DD)
  active: boolean;
  created_at: string;
  updated_at: string;
}

/** For INSERT — id and timestamps generated by DB */
export interface StudentInsert {
  first_name: string;
  last_name: string;
  photo_url?: string | null;
  email?: string | null;
  phone?: string | null;
  facebook_url?: string | null;
  instagram_url?: string | null;
  notes_health?: string | null;
  notes_family?: string | null;
  notes_hobbies?: string | null;
  notes_other?: string | null;
  holiday_until?: string | null;
  active?: boolean;
}

/** For UPDATE — all fields optional */
export type StudentUpdate = Partial<StudentInsert>;

// ============================================================
// Course–Student enrollment (junction)
// ============================================================

export interface CourseStudent {
  id: string;
  course_id: string;
  student_id: string;
  created_at: string;
}

export interface CourseStudentInsert {
  course_id: string;
  student_id: string;
}

// ============================================================
// Tags
// ============================================================

export type TagType = "yoga_style" | "studio" | "format";

export interface Tag {
  id: string;
  type: TagType;
  value: string;
  color: string;
  created_at: string;
}

export interface TagInsert {
  type: TagType;
  value: string;
  color?: string;
}

export type TagUpdate = Partial<Pick<Tag, "value" | "color">>;

// ============================================================
// Student–Tag association
// ============================================================

export interface StudentTag {
  student_id: string;
  tag_id: string;
  last_seen_at: string;
}

export interface StudentTagInsert {
  student_id: string;
  tag_id: string;
  last_seen_at?: string;
}

// ============================================================
// Sleeping students (from DB view)
// ============================================================

export interface SleepingStudent {
  id: string;
  first_name: string;
  last_name: string;
  photo_url: string | null;
  past_course_count: number;
  last_attended_at: string;
  next_course_id: string | null;
  next_course_title: string | null;
  next_course_start_at: string | null;
  next_course_studio: string | null;
}

// ============================================================
// Composite types for UI (joins used in pages)
// ============================================================

/** Course with its enrolled students (CRM homepage) */
export interface CourseWithStudents {
  id: string;
  title: string;
  yoga_style: string;
  format: string;
  start_at: string;
  end_at: string;
  studio_name: string;
  studio_address: string;
  students: Pick<Student, "id" | "first_name" | "last_name" | "photo_url">[];
}

/** Student with resolved tags (detail page, lists) */
export interface StudentWithTags {
  student: Student;
  tags: (Tag & { last_seen_at: string })[];
}