// ---------------------------------------------------------------------
// Course types — must match Supabase courses table schema
// ---------------------------------------------------------------------

export type CourseFormat = "individual" | "group";

export interface Course {
  id: string;
  title: string;
  yoga_style: string;
  format: CourseFormat;
  start_at: string;
  end_at: string;
  studio_name: string;
  studio_address: string;
  booking_url: string | null;
  created_at: string;
  updated_at: string;
}

// For INSERT — id and timestamps generated by DB
export interface CourseInsert {
  title: string;
  yoga_style: string;
  format: CourseFormat;
  start_at: string;
  end_at: string;
  studio_name: string;
  studio_address: string;
  booking_url?: string | null;
}

// For UPDATE — id required, everything else optional
export interface CourseUpdate extends Partial<CourseInsert> {
  id: string;
}